// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.1-0.20220609223533-7da811e1cf30 DO NOT EDIT.
package restapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	externalRef0 "github.com/openclarity/apiclarity/api3/common"
)

// Defines values for AuthorizationTypeEnum.
const (
	APITOKEN    AuthorizationTypeEnum = "APITOKEN"
	BASICAUTH   AuthorizationTypeEnum = "BASICAUTH"
	BEARERTOKEN AuthorizationTypeEnum = "BEARERTOKEN"
)

// Defines values for FuzzingStatusEnum.
const (
	DONE       FuzzingStatusEnum = "DONE"
	ERROR      FuzzingStatusEnum = "ERROR"
	INPROGRESS FuzzingStatusEnum = "IN_PROGRESS"
)

// Defines values for RawFindingsSourceEnum.
const (
	APIFUZZER        RawFindingsSourceEnum = "API_FUZZER"
	BITSIGHT         RawFindingsSourceEnum = "BITSIGHT"
	GRPCANALYZER     RawFindingsSourceEnum = "GRPC_ANALYZER"
	OASANALYSER      RawFindingsSourceEnum = "OAS_ANALYSER"
	OASTRACEANALYZER RawFindingsSourceEnum = "OAS_TRACE_ANALYZER"
	OPENDNS          RawFindingsSourceEnum = "OPENDNS"
	TALOS            RawFindingsSourceEnum = "TALOS"
)

// Defines values for ScoreExitStatusEnum.
const (
	GENERICFAILURE ScoreExitStatusEnum = "GENERIC_FAILURE"
	NETWORKFAILURE ScoreExitStatusEnum = "NETWORK_FAILURE"
	PARSEERROR     ScoreExitStatusEnum = "PARSE_ERROR"
	SUCCESS        ScoreExitStatusEnum = "SUCCESS"
	TOOLONG        ScoreExitStatusEnum = "TOO_LONG"
)

// Defines values for TestInputDepthEnum.
const (
	DEEP    TestInputDepthEnum = "DEEP"
	DEFAULT TestInputDepthEnum = "DEFAULT"
	QUICK   TestInputDepthEnum = "QUICK"
)

// ApiToken defines model for ApiToken.
type ApiToken struct {
	Key string `json:"key"`

	// An enumeration for the authorization type parameter.
	Type  AuthorizationTypeEnum `json:"type"`
	Value string                `json:"value"`
}

// AuthorizationScheme defines model for AuthorizationScheme.
type AuthorizationScheme struct {
	union json.RawMessage
}

// AuthorizationSchemeBase defines model for AuthorizationSchemeBase.
type AuthorizationSchemeBase struct {
	// An enumeration for the authorization type parameter.
	Type AuthorizationTypeEnum `json:"type"`
}

// An enumeration for the authorization type parameter.
type AuthorizationTypeEnum string

// BasicAuth defines model for BasicAuth.
type BasicAuth struct {
	Password string `json:"password"`

	// An enumeration for the authorization type parameter.
	Type     AuthorizationTypeEnum `json:"type"`
	Username string                `json:"username"`
}

// BearerToken defines model for BearerToken.
type BearerToken struct {
	Token string `json:"token"`

	// An enumeration for the authorization type parameter.
	Type AuthorizationTypeEnum `json:"type"`
}

// Finding defines model for Finding.
type Finding struct {
	// description of the finding
	Description *string `json:"description,omitempty"`

	// Name of the finding
	Name *string `json:"name,omitempty"`

	// risk of the finding
	Risk *string `json:"risk,omitempty"`
}

// Findings defines model for Findings.
type Findings struct {
	Items *[]Finding `json:"items,omitempty"`

	// Nb of items, used for pagination
	Total *int `json:"total,omitempty"`
}

// Current fuzzer report
type FuzzingReportItem struct {
	Description *string `json:"description,omitempty"`

	// List of paths that has been fuzzed
	Findings *[]RawFindings `json:"findings,omitempty"`
	Name     *string        `json:"name,omitempty"`

	// List of paths that has been fuzzed
	Paths    *[]FuzzingReportPath `json:"paths,omitempty"`
	Source   *string              `json:"source,omitempty"`
	Status   *string              `json:"status,omitempty"`
	TestType *string              `json:"testType,omitempty"`
}

// Report tag operation
type FuzzingReportOperation struct {
	Findings  []externalRef0.APIFinding   `json:"findings"`
	Operation *externalRef0.MethodAndPath `json:"operation,omitempty"`

	// Request count to this operation item during the test
	RequestsCount int32 `json:"requestsCount"`
}

// Current fuzzer report
type FuzzingReportPath struct {
	Payload  *string `json:"payload,omitempty"`
	Response *string `json:"response,omitempty"`
	Result   *int    `json:"result,omitempty"`
	Uri      *string `json:"uri,omitempty"`
	Verb     *string `json:"verb,omitempty"`
}

// Report tag item
type FuzzingReportTag struct {
	// Tag name
	Name       string                   `json:"name"`
	Operations []FuzzingReportOperation `json:"operations"`
}

// fuzzing status and reporting
type FuzzingStatusAndReport struct {
	Progress int `json:"progress"`

	// List of report item
	Report map[string]FuzzingReportItem `json:"report"`

	// An enumeration.
	Status FuzzingStatusEnum `json:"status"`
}

// An enumeration.
type FuzzingStatusEnum string

// RawFindings defines model for RawFindings.
type RawFindings struct {
	AdditionalInfo *string `json:"additionalInfo,omitempty"`
	Description    *string `json:"description,omitempty"`

	// location string token
	Location  *[]string            `json:"location,omitempty"`
	Namespace *string              `json:"namespace,omitempty"`
	Request   *RawFindingsSeverity `json:"request,omitempty"`
	Type      *string              `json:"type,omitempty"`
}

// RawFindingsBundle defines model for RawFindingsBundle.
type RawFindingsBundle struct {
	// Opaque data structure for the raw finding
	Data string `json:"data"`

	// An enumeration.
	Source RawFindingsSourceEnum `json:"source"`

	// An enumeration.
	Status ScoreExitStatusEnum `json:"status"`

	// Message giving details about the exist status
	StatusMessage *string `json:"status_message,omitempty"`

	// Raw finding timestamp format= date-time
	Timestamp string `json:"timestamp"`
}

// RawFindingsSeverity defines model for RawFindingsSeverity.
type RawFindingsSeverity struct {
	Severity *string `json:"severity,omitempty"`
}

// An enumeration.
type RawFindingsSourceEnum string

// An enumeration.
type ScoreExitStatusEnum string

// Describes the progress of an ongoing test
type ShortTestProgress struct {
	ApiID *externalRef0.ApiID `json:"apiID,omitempty"`

	// Progress of the test
	Progress int `json:"progress"`

	// Timestamp of the start of the test
	Starttime int64 `json:"starttime"`
}

// Short Test Report
type ShortTestReport struct {
	ApiID *externalRef0.ApiID `json:"apiID,omitempty"`

	// Timestamp of the start of the test
	Starttime int64 `json:"starttime"`

	// An enumeration.
	Status FuzzingStatusEnum `json:"status"`

	// Message for status details, if any
	StatusMessage *string            `json:"statusMessage,omitempty"`
	Tags          []FuzzingReportTag `json:"tags"`
}

// Test defines model for Test.
type Test struct {
	// A message in case of error
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// Progress of the test
	Progress *int `json:"progress,omitempty"`

	// Timestamp of the start of the test
	Starttime *int64 `json:"starttime,omitempty"`

	// risk of the finding
	Vulnerabilities *Vulnerabilities `json:"vulnerabilities,omitempty"`
}

// TestHandle defines model for TestHandle.
type TestHandle struct {
	ApiID     *externalRef0.ApiID `json:"apiID,omitempty"`
	Timestamp *int64              `json:"timestamp,omitempty"`
}

// contains all input parameters for a test
type TestInput struct {
	Auth *AuthorizationScheme `json:"auth,omitempty"`

	// An enumeration for input depth parameter.
	Depth TestInputDepthEnum `json:"depth"`
}

// An enumeration for input depth parameter.
type TestInputDepthEnum string

// TestProgressNotification defines model for TestProgressNotification.
type TestProgressNotification struct {
	ApiID            *externalRef0.ApiID `json:"apiID,omitempty"`
	NotificationType string              `json:"notificationType"`

	// Progress of the test
	Progress int `json:"progress"`

	// Timestamp of the start of the test
	Starttime int64 `json:"starttime"`
}

// TestReportNotification defines model for TestReportNotification.
type TestReportNotification struct {
	ApiID            *externalRef0.ApiID `json:"apiID,omitempty"`
	NotificationType string              `json:"notificationType"`

	// Timestamp of the start of the test
	Starttime int64 `json:"starttime"`

	// An enumeration.
	Status FuzzingStatusEnum `json:"status"`

	// Message for status details, if any
	StatusMessage *string            `json:"statusMessage,omitempty"`
	Tags          []FuzzingReportTag `json:"tags"`
}

// TestWithReport defines model for TestWithReport.
type TestWithReport struct {
	// A message in case of error
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// Timestamp of the last report received for the test
	LastReportTime *int64 `json:"lastReportTime,omitempty"`

	// Progress of the test
	Progress *int `json:"progress,omitempty"`

	// fuzzing status and reporting
	Report *FuzzingStatusAndReport `json:"report,omitempty"`

	// Timestamp of the start of the test
	Starttime *int64 `json:"starttime,omitempty"`

	// risk of the finding
	Vulnerabilities *Vulnerabilities `json:"vulnerabilities,omitempty"`
}

// TestingModuleState defines model for TestingModuleState.
type TestingModuleState struct {
	APIsInCache int    `json:"APIsInCache"`
	Version     string `json:"version"`
}

// Tests defines model for Tests.
type Tests struct {
	Items *[]Test `json:"items,omitempty"`

	// Nb of items, used for pagination
	Total *int `json:"total,omitempty"`
}

// Version defines model for Version.
type Version struct {
	Version string `json:"version"`
}

// risk of the finding
type Vulnerabilities struct {
	// Total of vuln
	Critical *int `json:"critical,omitempty"`

	// Total of vuln
	High *int `json:"high,omitempty"`

	// Total of vuln
	Low *int `json:"low,omitempty"`

	// Total of vuln
	Medium *int `json:"medium,omitempty"`

	// Total of vuln
	Total *int `json:"total,omitempty"`
}

// GetApiFindingsParams defines parameters for GetApiFindings.
type GetApiFindingsParams struct {
	// Should findings include sensitive data ?
	Sensitive *externalRef0.Sensitive `form:"sensitive,omitempty" json:"sensitive,omitempty"`
}

// FuzzTargetParams defines parameters for FuzzTarget.
type FuzzTargetParams struct {
	// service for the service to test
	Service *string `form:"service,omitempty" json:"service,omitempty"`

	// type of auth
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// username
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// password
	Password *string `form:"password,omitempty" json:"password,omitempty"`

	// key
	Key *string `form:"key,omitempty" json:"key,omitempty"`

	// value for key
	Value *string `form:"value,omitempty" json:"value,omitempty"`

	// token
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// StartTestJSONBody defines parameters for StartTest.
type StartTestJSONBody = TestInput

// PostRawfindingsJSONBody defines parameters for PostRawfindings.
type PostRawfindingsJSONBody = RawFindingsBundle

// PostUpdateStatusJSONBody defines parameters for PostUpdateStatus.
type PostUpdateStatusJSONBody = FuzzingStatusAndReport

// StartTestJSONRequestBody defines body for StartTest for application/json ContentType.
type StartTestJSONRequestBody = StartTestJSONBody

// PostRawfindingsJSONRequestBody defines body for PostRawfindings for application/json ContentType.
type PostRawfindingsJSONRequestBody = PostRawfindingsJSONBody

// PostUpdateStatusJSONRequestBody defines body for PostUpdateStatus for application/json ContentType.
type PostUpdateStatusJSONRequestBody = PostUpdateStatusJSONBody

func (t AuthorizationScheme) AsBasicAuth() (BasicAuth, error) {
	var body BasicAuth
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *AuthorizationScheme) FromBasicAuth(v BasicAuth) error {
	v.Type = "BasicAuth"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t AuthorizationScheme) AsApiToken() (ApiToken, error) {
	var body ApiToken
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *AuthorizationScheme) FromApiToken(v ApiToken) error {
	v.Type = "ApiToken"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t AuthorizationScheme) AsBearerToken() (BearerToken, error) {
	var body BearerToken
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *AuthorizationScheme) FromBearerToken(v BearerToken) error {
	v.Type = "BearerToken"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t AuthorizationScheme) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t AuthorizationScheme) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ApiToken":
		return t.AsApiToken()
	case "BasicAuth":
		return t.AsBasicAuth()
	case "BearerToken":
		return t.AsBearerToken()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AuthorizationScheme) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AuthorizationScheme) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retreive the annotated spec for an API
	// (GET /annotatedspec/{apiID})
	GetAnnotatedSpec(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Get findings for an API and module
	// (GET /apiFindings/{apiID})
	GetApiFindings(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID, params GetApiFindingsParams)
	// Fuzz a Target
	// (GET /fuzz/{apiID})
	FuzzTarget(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID, params FuzzTargetParams)
	// Start a test for an API
	// (GET /fuzz/{apiID}/progress)
	GetTestProgress(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Start a test for an API
	// (GET /fuzz/{apiID}/report)
	GetTestReport(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Start a test for an API
	// (POST /fuzz/{apiID}/start)
	StartTest(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Stop (cancel) a running test for an API
	// (POST /fuzz/{apiID}/stop)
	StopTest(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Retreive list of findings for an API
	// (GET /rawfindings/{apiID})
	GetRawfindings(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Receive list of raw findings for an API
	// (POST /rawfindings/{apiID})
	PostRawfindings(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Retreive a report for an API
	// (GET /report/{apiID}/{timestamp})
	GetReport(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID, timestamp int64)
	// Get the current running state of this module
	// (GET /state)
	GetState(w http.ResponseWriter, r *http.Request)
	// Retreive the list of tests for an API
	// (GET /tests/{apiID})
	GetTests(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Retreive last update status for an API under fuzzing
	// (GET /updateStatus/{apiID})
	GetUpdateStatus(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Update status for an API under fuzzing
	// (POST /updateStatus/{apiID})
	PostUpdateStatus(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Get the version of this Module
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAnnotatedSpec operation middleware
func (siw *ServerInterfaceWrapper) GetAnnotatedSpec(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnnotatedSpec(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetApiFindings operation middleware
func (siw *ServerInterfaceWrapper) GetApiFindings(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiFindingsParams

	// ------------- Optional query parameter "sensitive" -------------
	if paramValue := r.URL.Query().Get("sensitive"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sensitive", r.URL.Query(), &params.Sensitive)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sensitive", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiFindings(w, r, apiID, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// FuzzTarget operation middleware
func (siw *ServerInterfaceWrapper) FuzzTarget(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params FuzzTargetParams

	// ------------- Optional query parameter "service" -------------
	if paramValue := r.URL.Query().Get("service"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "service", r.URL.Query(), &params.Service)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------
	if paramValue := r.URL.Query().Get("type"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "username" -------------
	if paramValue := r.URL.Query().Get("username"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "username", r.URL.Query(), &params.Username)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// ------------- Optional query parameter "password" -------------
	if paramValue := r.URL.Query().Get("password"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "password", r.URL.Query(), &params.Password)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "password", Err: err})
		return
	}

	// ------------- Optional query parameter "key" -------------
	if paramValue := r.URL.Query().Get("key"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "key", r.URL.Query(), &params.Key)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// ------------- Optional query parameter "value" -------------
	if paramValue := r.URL.Query().Get("value"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "value", r.URL.Query(), &params.Value)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "value", Err: err})
		return
	}

	// ------------- Optional query parameter "token" -------------
	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FuzzTarget(w, r, apiID, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetTestProgress operation middleware
func (siw *ServerInterfaceWrapper) GetTestProgress(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTestProgress(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetTestReport operation middleware
func (siw *ServerInterfaceWrapper) GetTestReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTestReport(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// StartTest operation middleware
func (siw *ServerInterfaceWrapper) StartTest(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartTest(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// StopTest operation middleware
func (siw *ServerInterfaceWrapper) StopTest(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopTest(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRawfindings operation middleware
func (siw *ServerInterfaceWrapper) GetRawfindings(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRawfindings(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostRawfindings operation middleware
func (siw *ServerInterfaceWrapper) PostRawfindings(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRawfindings(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetReport operation middleware
func (siw *ServerInterfaceWrapper) GetReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	// ------------- Path parameter "timestamp" -------------
	var timestamp int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "timestamp", runtime.ParamLocationPath, chi.URLParam(r, "timestamp"), &timestamp)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timestamp", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReport(w, r, apiID, timestamp)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetState operation middleware
func (siw *ServerInterfaceWrapper) GetState(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetState(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetTests operation middleware
func (siw *ServerInterfaceWrapper) GetTests(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTests(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUpdateStatus operation middleware
func (siw *ServerInterfaceWrapper) GetUpdateStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUpdateStatus(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostUpdateStatus operation middleware
func (siw *ServerInterfaceWrapper) PostUpdateStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUpdateStatus(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/annotatedspec/{apiID}", wrapper.GetAnnotatedSpec)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/apiFindings/{apiID}", wrapper.GetApiFindings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/fuzz/{apiID}", wrapper.FuzzTarget)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/fuzz/{apiID}/progress", wrapper.GetTestProgress)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/fuzz/{apiID}/report", wrapper.GetTestReport)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/fuzz/{apiID}/start", wrapper.StartTest)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/fuzz/{apiID}/stop", wrapper.StopTest)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rawfindings/{apiID}", wrapper.GetRawfindings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rawfindings/{apiID}", wrapper.PostRawfindings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/report/{apiID}/{timestamp}", wrapper.GetReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/state", wrapper.GetState)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tests/{apiID}", wrapper.GetTests)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/updateStatus/{apiID}", wrapper.GetUpdateStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/updateStatus/{apiID}", wrapper.PostUpdateStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.GetVersion)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc7W/bNhr/VwjefdgALcnW3n0IcB+U1EmNpbbPdjrciiBgJNrmKpEaSTlzC//vB75I",
	"oiTKlvPSBl2BAYtN8uHz8nteyIfuZxixNGMUUyng6WcoohVOkf4zzMicfcRU/Y2SZLyApx8+w39yvICn",
	"8B/H1bpju+g4zOWKcfIJScLoTH2Jz5DAcBt8hhlnGeaSYE37I96o/8lNhuEpFJITuoTbAK5RkmPPyDaA",
	"HP+ZE45jePpBLy8m3wTFZHb3B44k3N5sA+hhRZGNiYg4SQlFknH1RYqyTO1Qk7dDumI8gGdIkEht0TW3",
	"mhDAM4w45jtJu1O2QaGrzQgpro142wAyinsYodpaqX2nuQqB9k2ssdehXW3o06adjWUOQM18k+EBzdOW",
	"yTWltq0bvJTLla2xsnWmvoanMKQA0zzFXM8DC8aBXGGA3NVAEQcZ4ijFEvMjGECsiX2AZ+FseB5ez9/C",
	"AIaT4Xz862CkbDsIp4Op+aSYIzJR3LV4gkEb6w6Int7BMiTEPeOx18tygTlFaQ9HK2cGFUW/w9VQ/vTy",
	"yILwbn7NND+HF4TG1tXrtGtAaeLG+QTYQmNmYQlV9n7jLPFYutB1nbLy7m6SI6P1Fi1OxMc2LfVtN62p",
	"WhN4VFdMuKiWNN3LDom22ojEaf2PXaYutnB2Hep15Z6Ic7TR40yixKOvOyWh3iwAucCxduIMLVU0t5q3",
	"lOeaQkmZUImXmPtEFl6Z80+fCF1Occa4VFy2mTnPOcdUgkX+6RPmgOupMNiNrJYxF45y6/SviJBK3AzJ",
	"lQByhSRYIQHuMKZmzxgG/RQ/RfelrI78E0XYo/yOuKD8Xy14RkZrWlfs9WFXsJxHfoaFRDIX3iGJhZzb",
	"1LTDK1ow2IeVcWbzS1tPZgKQaAlYOauJFxcPTZ0dHR03/kMZeaUUmTJ6zDJMUUaONihN/KF2MvS4YIEM",
	"kBAhPeplrkBPw8g7LFcsDmlcmFjFbyykOGc5lT7F6WEQqWEgGZArIiod6oAA4lxZT4c/ZVsYwAXjKZLG",
	"+V/94gbDNj2syCF/vHCzS51Tx31vXPJeO+/GjVbFA2NMhjYJQ/5Ez7HIGBW4azBPpDNUih3AnBN/fY75",
	"3QFOo+XaJ/wcLXe6CzGeV5fan1LnaAlsuVKmAuerpjSlgQ5IY353dxRQftnhVA1MWd4cVvxgIrvjz0wH",
	"u5DGZklbNQszD5ioCBCNLaBM3m9girMlx0L4wcHLLVAcE0UfJZPa+t4a1FF1G3TkFLNRKXpNKT5dVBG/",
	"BwNGY96zhqVTShpUCrlpIb2p+X026nM8cU8eb8ajAQzgYDodT2EAh6PbyXR8OR3MZp3M+LDulgGtUq6y",
	"45AumNfz95UyCYs6Ml8xAsxkIO0huvS3dnp2kz4oKfuLFZGhqCvA6XB9QIE0w2vMiTRV6N76wFWpx+rO",
	"8FlO48RzPI6RRG2FjTP0Z46BGlQ6yyOZc1yeWDm6951AFCWP2av6qK8K9ALjFn09ahYxjgd/Een6VLH4",
	"NsVCoKUnWr8zA2BJ1goXMZaIJAKgO5ZLLSr+SwWC0hsLWc0uwC73SS1JioVEaeZJLJX6QDkNmGrhP0rn",
	"+Cf1tZtBSmLBntOnw2m1xFogMMa+8cLH4mM3iEpwtmAknJEmhw0alXUPCEFnw/lsePl2DgM4D6/GMxjA",
	"8WQwejPSf4Wz23AUXv1vNlDx6XI6OTeff9ef1fB8Gp4P3C/DyfD24vp39cGvkFmhtJZpfVg7QJTZ9fm5",
	"Cp0BHA3mv42nv95ehMOr66kKsfPx+PZqPLqEAZyE09ngtoi5l4PRYDo8L6c6PPvY8XG9UoUOFnLiZNY6",
	"z+YO4Q4LDf0i4ag0iChgdMk0Yk1x24jeGRm+ecKTgia3DWpVQJ3XicOdU3On6C+SKj3/fHISwJRQ8+lk",
	"z0WJU1oIibjU/teu7UpntZvquQ0O3Kr/36/rMUMVUsQtBLvK/IoJf+LXxgTKmqBURHfyL03fVZk55Kb+",
	"Ev+5DPx1tP2IOq1Y+m5fSlHJ0la6Nq0EgChP2rTziM1PxURvPkHLBx4R1OFmWzuN9DsWuBis0gpadgGx",
	"G39zWwLVIYU5Z7xTjWGpFEJBhIS+p9RLHPUNXBIepT1D+Cij58uJHQFc5wnFHN2RhPQ5/7xvTHcryjkW",
	"nTZ8i/w15HMFh1oN1daN52bVx/WQZrkn5kWMSkSoAChJAFFzqraL0N6LOnKd7Zcc2FUwJ5hs/9qS5zdq",
	"tvd0aOjc7BK4WtynD2Xk12T9zaf/Xg/Pf4UBfDO4CK+v5vqvwcSNBPWdfd7oFh8jJsmCVOe1VrPmkRg6",
	"QwLX9tjXYGyXR7pjU2XNl8uxDbwlv78Ruaoy/RcPugkqWJr3i4RqQXHRwnGEydo2Vp4gMn6FArK6m+pd",
	"WlRXN99+EiF0+Y7FeYKV6J5kEk6GYkjPUbTC/ru/NebCfwXUiJLFxKBGsytqPrq9qIV+Kb1FI5FH1PeV",
	"9urCHqxWnyLftzHUp0tc5yTiRJLIpyMtuFqusOoo5LxY4cP1iixX/Um9VbN9ZBJ235/KFbv3EklxTHwp",
	"uYvOOzPfR6oDRl2UemCm3qMvjKpmEHsl28gWk+F5gjiRGzBJ8iWhF6ZLFE6GzsYds6DjyPDk6OToZ9sO",
	"UVkSnsJXRydHr6DT8z1GlDIVMmKR4ej4sy46t2pkib09O8lVJjFPbIqlQK01xR1VfNoTWQBen7wGIybB",
	"BctpDJhcYX5PRK0tMozhKbzEMiyIzTIcaQ6LqlFXA0Ttnpmuk2kR2frY9SLJcxzYl25PXjhvb6q2m1bd",
	"Lycn2q8Yldj0N1GWJbbOOP5DGK+vuKlrUquMUKDm2VtKP0r8HRSpI9E2gK9PXj+CC12FFOWJ5xq0tb+y",
	"DqBMgoUyqQa6yNMU8U1vdBTn3dMPuoOQ/GTaoPBGEVOmKe4K96IxFB/NmaLo19pLNcc5Up0UA90WCyfD",
	"IzBMswSnmCrG7jYAo2hlJ3lRWXHzIjEZPJZgJdLxDFNBJFlj+GioP/XLBuGDYmhiTfnSwd6163kLZDvg",
	"X5rljEyL1ryHZV3kA17NcL3nEssKyE4wVdC1CNUeotxlr2uodAAQmCOuhpvIVqPl0ItEdSNYYr4mUdUq",
	"Kz5LVpTnmus/c8w3Fdt2FnQZbRVhza30S1EVRswbXx9dad59HkDUeW3pI+gMH0C0fLfpJ+oMH0DUPMD2",
	"0TMjB5DSr7i1ybqJmpfehxmo6DL7LGPHusm1I9trz8V9HkVYiEWegMqbVao9+ZKp9gzFtjDAMaga4l8h",
	"51tvc9J+AP/1ZZUxpFL5SAJ0CG1Ezmaw21FeuMHz2L3G8EZRc7Y3N5b1CqZVKdQuub7F8vXAaz4PjLq8",
	"6juYXTB3Y66AdTegq0uyp4Bz1bT8e4K5uDz8DuWvAGV9B6vv05h4BJT1PHtx+kJhrN+ynbF482QIrvpz",
	"2+12+4yu4rQvv3vJ1/ESlu1yEpaBHyJEI5z8CBDgOaXFY6PdTsOyl+0zD67gv0OvDr2+APFCkaP7Rd+7",
	"uqlpQeo3Mup87bnp8NUh02oL+IyBrP1k06PKKbovbpvKyyb//eduITuOJy/U2fyhpWlO5/HyTpNOmGjZ",
	"9OkTYIc561rbPjiQNIzeVxM7jqWmcC/D+ufyjU6PVgwquvxuAybGVJIFMZfcRArgvlxue9nLrfSDB3Xr",
	"PYy7Cuhmfv97qJtnrqecdyb7+z/+8ONBxG74ieLRgBdpl1iCXGDlA4QaBelfQVXv+SP7g7Yif2h6rknU",
	"l91dFvNm4Zn12ngh4dFt8bO8OsN1oTx39nsUQETt9l4b7rA+a+La3PXyH+6JXCkbGHP/2HWQ//tdSM2t",
	"ezzMf3Ypfbcj5VmMJDbPj/obWT/VMkuLx82OlXMaYw7sz/x8Jr52Nn1OL+p6XPWoSukg0b+FymnC2ZrE",
	"BmTXD7O5KqJaRn/6KmqXvZ+llLp+JA6UBzoPrjqTmVK9nVfG6Hed2el9+eDt2Tyr2MLjSu9dPnHBpj8L",
	"dcikqQrM14V7NH6VuMacK0TeIYH1P/dgVJ8kwPnxcgBznsBTeKxfB1gDNEkN1phv5Eq5vSkOyldJ1gut",
	"qdpVnfnHA4R5one3cZ9wXA+r9TWDb2+2/w8AAP//Ho1J2eZKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../../../../../../api3/common/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
